version: '3'

services:
  service_db:
    image: postgres
    # restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    networks:
      - networks_clake

  service_backend:
    build: ./django
    # command: /entrypoint.sh
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - ./django:/django
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - service_db
    environment:
      DJANGO_SETTINGS_MODULE: ${NAME_PROJECT}.settings
      NAME_PROJECT: ${NAME_PROJECT}
    env_file:
      - .env
    networks:
      - networks_clake

  service_frontend:
    build: ./reactjs
    volumes:
      - ./reactjs:/reactjs
    ports:
      - "${REACTJS_PORT}:${REACTJS_PORT}"
    env_file:
      - .env
    depends_on:
      - service_backend
    networks:
      - networks_clake

volumes:
  postgres_data:
  
networks:
  networks_clake:
    driver: bridge