# Generated by Django 5.0.7 on 2024-08-03 19:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('monthly_consumption', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospective', 'Prospective')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField()),
                ('state', models.CharField(max_length=2)),
                ('cost_per_kwh', models.DecimalField(decimal_places=4, max_digits=10)),
                ('min_kwh_limit', models.PositiveIntegerField()),
                ('total_customers', models.PositiveIntegerField()),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('terms_and_conditions', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarke.client')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarke.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='suppliers',
            field=models.ManyToManyField(related_name='clients', through='clarke.Contract', to='clarke.supplier'),
        ),
    ]
