# Generated by Django 5.0.7 on 2024-08-03 17:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('monthly_consumption', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospective', 'Prospective')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField()),
                ('state', models.CharField(max_length=2)),
                ('cost_per_kwh', models.DecimalField(decimal_places=4, max_digits=10)),
                ('min_kwh_limit', models.PositiveIntegerField()),
                ('total_customers', models.PositiveIntegerField()),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
            ],
        ),
    ]
