# Usar a imagem oficial do Node.js
FROM node:20-slim

# Definir o diretório de trabalho no contêiner
WORKDIR /reactjs

# Copiar package.json e instalar dependências
# TODO: 
# COPY package.json /reactjs/
# RUN npm install

# Copiar todo o código da aplicação para o diretório de trabalho
COPY . /reactjs/

# Construir a aplicação React
# RUN npm run build

# Servir a aplicação
# CMD ["npm", "start"]
